### PR TITLE
Don't redial mux when stream times out

### LINKED ISSUE #626: Investigate `underlying connection was closed`
Lots of shards  fail to download due to this error during migration. I ran the following command to see how the failures are distributed sorted by occurrences. 

So far I've only noticed that these happen in batches for a host. e.g. 30 shards for different slabs might fail at the same time. Which makes sense if the underlying tcp connection breaks for some reason. 

I marked our own hosts in that list and checked out Atlas. e.g. running the following result shows that according to Atlas, Zeus closed the connection:

```
debian@hostd-atlas:~/deploy/hostd$ docker compose logs mainnet | grep "peer closed underlying connection" | grep "<redacted>" | wc -l
6348
```

List on Zeus ranked by host:
```
docker compose logs indexd | grep "underlying connection" | grep -o '"hostKey": *"[^"]*"' | cut -d'"' -f4 | sort | uniq -c | sort -nr
 23728 ed25519:fc7750f91620990efa30d8694f313a08f3bcd197357498b394b4c40ed4c25f9c
  23636 ed25519:3f05e711c6fb414555b3957fdcb74643bb6dd34ce4f94442ffa2f5eeff90922c
  22577 ed25519:b67b8c33e7efb8f8285bb01284f652d1a1d06177957329c37e48b217dceec639
  21094 ed25519:0db2166263513523bc04b865c94aef3f0a60bd0a2243f3b47cdac1e857b464e5
  19769 ed25519:fd5f6e1ccef423502a9d9ecf9eaeec861a84507ebd96dd0b81767f1a5dfbcdaf
  19386 ed25519:8b7b9bb2c636b872a5d6fbafcf64da6cf0f265fb928ca996be8edf3716f566b2
  18746 ed25519:9167094dc19fc706ce10405baacc8072c1d35fd8433e9e4be93158d15d776183
  18678 ed25519:1dcaeab5f47c506a6947cf7f532b52b25f6ea82919e5724be88275457e6a3057
  17931 ed25519:9e12f3cbd436d5d1fd037a159c28c7265a0cd327fd63a64dac7d0fbad6d3d582
  17786 ed25519:4298a298dd84bc48028f7bcf267e8b779a41fa671df3924cf47199fc7d344e2c
  17275 ed25519:4e3a30c4e38f4e9e806eb1495ff9b5ca30f9f9f186c9dc18955ec883ddbeeb4a
  17173 ed25519:c8100e62d9bf5de75ce874ef9b23e23da5afbab1d988e25dd7c528b09f1522fb
  16705 ed25519:05f83ae1236c063fc6a14ba8c6771f7ea1e326f96ec69b6b49e09157ee602121
  16258 ed25519:1438b400373cb0507489d2001a224c04559bfff866fd0081b2249c124cc2cdc2
  15850 ed25519:e96d77aaca114f1b0b6d4e7996d60f3a6750825b86aea3cabfb102c3190e1639
  15537 ed25519:a213e30c8243b299e5505f82c9a87d791767f1d0fc1bdf448632138c88a8bfab
  14251 ed25519:df461bb7e1f6039a90f6a227f0f30b3baaa6b509548d67081605e3edcecd872c
  13531 ed25519:7f7000041cd55d9ca4f8be9c7e587bb4e4a79b320b699a05b723eed9b1104b64
  13257 ed25519:d624c6db542ca8be19f4f51b05896b081ff801c18785443eec9a3357866d195c
  12655 ed25519:335b601a3b9799fbd185210c4351f9b29245ae7433575cef6090c902bc7d6450
  11416 ed25519:365c507e918960b3b73be218384ed61d58b2e8e6d5ed86242b23e5312e04c280
  11335 ed25519:35e4a78314ccc770a99309b50ba3e58405aa4b9ba346b484c79a1dbc97282fe3
  10821 ed25519:a45e96c7019be76a7aa57f508b683cf7da2dff603d7b3fda63009016a53b0ca1
  10519 ed25519:dbf7e95b4ab57507b509320edeb3a171b8631cf46980591c1c673d7514925077
   9481 ed25519:ea6fa149022d645714927c2ac577afb748ee5efb55cbd8ae5b833a6eb15fc3fb
   9172 ed25519:72e8ea2c2de3987608c360b574327c201ecbe34037dd47d51135370828650706
   9045 ed25519:d875d47ab91f5da7e0b7a93c8e10fdc2ab0607ad676d828c30de1b4f48039210
   8219 ed25519:3f39e8be4206ef20cb346602feba81d366fcd7ce64a225f4b44c7e6c73be1075
   7291 ed25519:14686caf06eef356f13c5a31eb162fd91f4aaf548fc4624bf26976b6fc3bb3ba
   6892 ed25519:eb3720b49a47a17b9d6d38f6efd1ba493bdba3cac78525c2819165e09406cb9d
   6585 ed25519:acaaf26865ab44460b20ca6e3326a77d961f627f74b3586484c5916775ade9ea
   6507 ed25519:66d86d4dfbb1434304240e15853e481afd277379c42b812a17cb18bd90ac5597
   6181 ed25519:4db02cfad0d4492dce315d06c5a7cfb5d384a72297f66f84bb3dea518465ed03
   6116 ed25519:2addd5035bb22992038a7d981b4da6cb329a80cb5b7ecd5adfa50a48e470e215
   5818 ed25519:868e4ba83ba498c91c2f932e6f3fa2fbbb4d75135b9abc5aa20cbd7d3053f202
   5570 ed25519:cb807bf0edbd86b865aedbf9948ea46949c090a74ce0e1effb5343b0c44f6df6
   5569 ed25519:1b7913f49d5410a99dc184a7c88e2a638eee94c87b6b3af5cb61c3e9a4c13212
   5501 ed25519:499b6fbdc0b79462d77731a0fbdedaebdccb42ff411d1673cf37b56f696244de
   5444 ed25519:5457df80d247691e51778642d7c93bd7a3aeb0025c5f0d3ee174904265fcd94d
   5413 ed25519:e6778eb3b2788233cebb24b8bbf44e55bd85ce884aaa00a718c27f0cc57653b9
   5314 ed25519:154bee9ca48de47704da0c839418e803d467f861147a4e7e43dffe5b97d3c7b2
   5154 ed25519:783c49d3a116c694bcbf2c88323f9bf4f5a444a3866bd327182e3a6a92a446b3
   4511 ed25519:30860343bc13f595aabedc4228e0da3accb9e2042336b87361770dae761533b1
   4428 ed25519:ae9e41bd163373ce6977680951a2b97e4317523ec770acb349cf94af1d52d315
   4254 ed25519:887e01c621e7fc68514fd6c0c991aba961ad73066219eb3bcbb784bc1653c056
   4067 ed25519:8739bc1a4b0125bfe5b7d427d1a5aacd34ffd417c63c709db108487df60074f7
   3910 ed25519:71a2d4727ad52320820db9429c40dbab5a5ce58011ea4e75dcbd13184ef56285
   3805 ed25519:4c378804651dc9545d3abc74254f60530f1a9fad73949001d5d5a404d3928a97
   3722 ed25519:adae50da5abf55640ea125c9a733fbdc93d67f015dffe340f808ac2383841565
   3629 ed25519:4f194b68b943204bba1ac79a400414058c5d5f1da122d31e375da9316aff63ef
   3529 ed25519:e087748cc0ba7ee051e06025f19b5707f23626d063a4ffed81c0afe75c8fb046
   3213 ed25519:e47a15723f58ef5c8bdb2e17e5554cccedb259cbb2585b57032dce92aa8cbf45
   3121 ed25519:9e5bd3690c2cde02d8b0d6c84c081b018424cc566244a7a7e1f25a7e5c686d4b
   3061 ed25519:1648ef6f3ea1c1d03d2abeb033de0b54cd138bca3ceefaf5af30df2b79711908
   2899 ed25519:fba406818f558676e117323f45665f3affbb10bb025f74548fafe66df0dd5274
   2868 ed25519:aed9286d471f16289370cd79e0165e4933190c9e4609833ad2a701ff52966945
   2702 ed25519:0e43d3e26c6a9f112e7ec2edabc524675c17f14b4d387d50749803c2501d03dc
   2528 ed25519:aa0321bef5823e24662ecceddc475041fd0c52ff0e4a9258af563cf9b8c100c4
   2516 ed25519:88417ffb8364712841cfa82151c9849b939300f1147209a79b0df1773ee09327
   2293 ed25519:f166b306fbbcc6a774aead9605e2e9187ed660254a513d68f282a722a4c6b74c
   2150 ed25519:971811e42f0ea024623f277a5c677a2000a982ae0ec61cf7ad3ad9f37ee9cf5c
   1893 ed25519:20a79a1287530c1c8c4066783d3f129c949aab4eb59edac5d1b44baf2d1d109c
   1860 ed25519:efa5c602e4d675c2fb63646d70861a21a6f60d6b5f65f228dda8b5087457051e
   1844 ed25519:c7a0b59262eca12e213d86ab1c4252e76b7b5bc3a7fe5e6c6affeb4bf15cc423
   1731 ed25519:c44ba129e35fc5ed63412b3348a5df5deaec0a402a88ae20084c67c846291f9a
   1720 ed25519:92d727b540516b84532861df3f837a354765e43ba671da87d0e2052f9dac7e41
   1531 ed25519:fd9090f5973fc92410e141d2ca7112f266a5f9e5aca9a7024f4116b5a3504274
   1388 ed25519:65aa23c624ba89efae472925c7d515cbc842dd5f2cec56e593d42088bbdecb44
   1369 ed25519:ef9af9844b389d6c740df5418a3fa5dedffc2ea127edf7c109f6698b6f210f97
   1349 ed25519:1d93e1ed57dd37adce6a068a9aae4a412de062bacf3706d883f667643f1a7d45 // <-- This is Atlas
   1273 ed25519:b009d80a2bbd7b37db3a44b51b6fc798612fc8b74f07effa03a5d75331bf7cda
   1247 ed25519:a4458450c6c677c52256ba9c08d04322e00ce990e317d4c345bee274febf3f6b
   1246 ed25519:7c8a3f78c28861fead7010935ffd3a92b1f8f6f396b1f4c973cd7c395579696d
   1156 ed25519:75615c81f6de6506050bedb42d121b30761dc2fe6a45f0c02ad665c2df68294a
   1074 ed25519:c9b1f8a3d692fd1f713cb52630d27518178b8054a7bc1d65dbe123fc4a1d639e
   1003 ed25519:97541e985d72fb9151bcb9f50f413138803c0a1adb899d2064bdaa91f1011c3a
    872 ed25519:7d0a8abda412bdea1b89847d9312fcef2750479ee4f9ef96946f0f61ca1886be
    823 ed25519:f18bbe5b58b133c573928b20b0d6c1eb461b5e583061a8c3d52f5e2c82acdddb
    642 ed25519:97da923688f0ba983321697904ecb3649712c390a69fd662f70659c63981a06d
    634 ed25519:08889c377b0a989638142383cede1ad80d5c59467bb76fd1ede833c9ac62ea97
    561 ed25519:381423994909daf6cbd1a779fb73f40b1b034adaf64fb9da62a0f797ecdc624b
    540 ed25519:50bca4be99b3131d80eb674566db67ba95f3251e2f29265ac2e8acc640e24444
    515 ed25519:98b254cb71a857bddc15638b8256d4257e60906c10bcef080612649c116889c9
    487 ed25519:a94e6819e9663a65e05ccfc1d4e5a765c1647cd8458b8e821c3a00a05fd0e684
    466 ed25519:0efd14164201d79231a45d3148630c6efa3d9488c0457de3666dcb6af18c2cfe
    430 ed25519:5788e40e646611f7d6ab0f1db6036a270e7ef08a5d238b598578d500b17a9124
    395 ed25519:9f07d30eb82cab84822e3367b0b8f21d905ffc8556e011fa00de75b5c905f8cc
    359 ed25519:5511c9b35360e3fff35273d5c0236a4905496f93f22cdca1de0cf86d1f5df5fe
    306 ed25519:be5965c5f52542ea6016875ed4a46cc1173abbced2be47b39f91991f0b21db96
    278 ed25519:a8544ee30760baa192a0dd32a34be3cba62f73d9b6562904f4d681491c8b1606
    268 ed25519:d8ab5fdc4aa3c7ba47526d565b318dbad98f25fdfc1934e995ccdb266b05d0d6
    262 ed25519:edb83bee864a7c6d766b4a7cad57309d93893136c77044f805ce044ca5075db0
    248 ed25519:c816a73c9c30e7cb2aa060135dd6771142980f3eccb8b8862b4b21f421ac3f97
    243 ed25519:3794d9438e79cbfa16c419c367e4c18ee6b34f5f8a7670e2c3dd485c16787297
    187 ed25519:d5969e5ef0c4d83625bbfadd6db658d895bd45042dc952b89ae8afecf89c096b
    165 ed25519:11db70175a03821211f3364083c2c43defcdf61412eeb2f847f83380b312c907
    159 ed25519:cdc7546efacb4da41a5239199873c73f67579cad43354fb085611bd7e375a1ec
    157 ed25519:b7f7eefb28aac62139ad1aa3f5eca696fc27100ba99fc6e58d38d2c43eccd659
    156 ed25519:5796cf73680883c627ebdd265ba77a05b4847aa4c8020ac2278a8c74ab0e52aa
    136 ed25519:e8b5b2b19538276be18ce44d66211f4e571447fa071f119c527ce7e18ee4c1b7
    128 ed25519:3128aca726a83738c089369fd4dbda1dd73d7c96113b90bd381ba69e1738fa48
    128 ed25519:1b473a2239c5290d45680ed1699795d94481a7a22b981d2c9a1456d1dd2dd699
    120 ed25519:ce8272efd45f1f6e6d1c7a20ee43eabad83284983ae530f7d162ea654dccca9c
    119 ed25519:c761cce8a6a7c0ed4f3824ac5d71076a515152bf234d936a22a1734fb4445bcf
    112 ed25519:d6ce5cf234477675467f592303e779f578807beecc501933b02a376030cf2102
     36 ed25519:da2e16500a5413f31170a37334e91eeccf38af620861991bad21a9e9eb9061e7 // <--- This is Athena
     34 ed25519:dbc344464fbde26e3ae5b6243c0d5d23d0272465dd778b9a6a1b4a95ec6247a6
     33 ed25519:18af96efbdad0ee716a38f53ef794d6f92552c1b9ed3300cfff60199faa5e8d5
     32 ed25519:2cac81bb979c999c6dc9ffc8b74ee2bb082b46e98ae306d30696fe4c1a823005
     20 ed25519:36f84c5e6a52d44d2bfa51a84bdb5f2c5b7522a70c1b9e106b7ec84f10476c72
     15 ed25519:b7cbc560e8f389eb91702cc18ff38d4434d4e91ef03f201b5521dbf415a092bf
     15 ed25519:54292cfed80d5bbd5dc9f0986ead13c6d46f35817639756fecb87e8d3ecda4f1
     15 ed25519:199acb6bc7e7a3e4782b55442ca4fd1d42cf1d35bbbf879f1f28b3b88b4e2c00
      2 ed25519:f54367610e7917b51e9a731bba11f68a4570415e3518901d6e89c6912e1b2278
      2 ed25519:e707b20f95a2ddd58d0dbd98d75cbc8d179187f1842f3aeadc0d612d1654f926
      2 ed25519:36c8b07e61548a57e16dfabdfcc07dc157974a75010ab1684643d933e83fa7b1 // <--- This is Zeus
```

### PR DESCRIPTION
**Pull request by ChrisSchinnerl**
Fixes https://github.com/SiaFoundation/indexd/issues/626

Turns out that every time a stream was closed due to being interrupted by a closed context, we went ahead and closed the underlying mux. Leading to every other stream from the same mux across slabs failing as well.

Fixing this turns all the `underlying connection was closed` errors into `stream was gracefully closed` errors which we now don't log if the context was cancelled since those shards are expected to fail.

### CODE REVIEW

File: sdk/dialer.go [hunk 1]
```diff
@@ -328,8 +330,17 @@ func (d *dialer) retry(ctx context.Context, hostKey types.PublicKey, fn func(rhp
 	}
 	if err := fn(tc); err == nil {
 		return nil
+	} else if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
```
Comment (peterjan) [inline sdk/dialer.go:333]: If you added this because it was missing in `slabs/dialer.go` it's a good argument to deduplicate this code in a F/U. It can be a low prio issue but it should probably be tracked.

File: slabs/downloads.go [hunk 2]
```diff
@@ -114,11 +115,15 @@ outer:
 			usage, data, err := m.downloadShard(ctx, host, sector, pool)
 			if err != nil {
 				lost := isErrLostSector(err)
-				log.Debug("failed to download shard",
-					zap.Bool("timeout", time.Since(start) > m.shardTimeout),
-					zap.Bool("lost", lost),
-					zap.Error(err),
-				)
+				interrupted := ctx.Err() != nil && (errors.Is(err, mux.ErrClosedStream) || errors.Is(err, ctx.Err()))
```
Comment (peterjan) [inline slabs/downloads.go:118]: why is it ok to drop `os.ErrDeadlineExceeded`

File: sdk/dialer.go (hunk 1 above)
Comment (ChrisSchinnerl) [reply sdk/dialer.go:333]: There is already an issue for that

File: slabs/downloads.go (hunk 2 above)
Comment (ChrisSchinnerl) [reply slabs/downloads.go:118]: As mentioned in the comment, the stream will either return `ErrClosedStream` (when the ctx is cancelled or times out) or `os.ErrDeadlineExceeded` when `Stream.SetDeadline` times out. 
You can find that in our `mux` repo if you grep for `os.ErrDeadlineExceeded`.
