### PR TITLE
Atomically update host usage

### LINKED ISSUE #491: Update host usage atomically
Right now updating a contract in the database and increasing host usage is not atomic. So if we fail to persist the host usage after revising a contract, the revision in the database gets updated while the usage remains the same.

We should change that by searching for all calls to `UpdateHostUsage` and merging that behavior into whatever method we call before that to add or update a contract.

### PR DESCRIPTION
**Pull request by peterjan**
Fixes  https://github.com/SiaFoundation/indexd/issues/491 &  https://github.com/SiaFoundation/indexd/issues/469

### CODE REVIEW

File: client/client.go [hunk 1]
```diff
@@ -282,7 +279,7 @@ func (c *HostClient) WriteSector(ctx context.Context, settings proto.HostPrices,
 	return res, nil
 }
 
-func (c *HostClient) syncRevision(ctx context.Context, contractID types.FileContractID, revision types.V2FileContract) (types.V2FileContract, bool, error) {
+func (c *HostClient) syncRevision(ctx context.Context, contractID types.FileContractID, revision types.V2FileContract, usage proto.Usage) (types.V2FileContract, bool, error) {
```
Comment (peterjan) [inline client/client.go]: This little change essentially tackles https://github.com/SiaFoundation/indexd/issues/469.

I want to draw attention to it because currently we still would not track usage in the event we fail to revise the contract, accrue usage, but then afterwards fail to fetch the latest revision from the host (or if our local version is newer for some reason). I think that's a bit of an edge case and maybe it is fine to ignore that usage?  

If we really want to track that, we would have to add a separate method on the store only to update the usage and that's kind of sad. This whole PR is about atomically updating usage when we update or persist the revision.

Updating usage currently only happens in `AddFormedContract`, `AddRenewedContract` and `UpdateContractRevision`, which all make sense. I even briefly considered merging everything into an `UpsertContract` but it gets messy.

How do you all feel about that?

File: persist/postgres/contracts.go [hunk 2]
```diff
@@ -139,14 +134,24 @@ func (s *Store) AddFormedContract(ctx context.Context, hostKey types.PublicKey,
 		} else if resp.RowsAffected() != 1 {
 			return fmt.Errorf("expected 1 row to be affected, got %d", resp.RowsAffected())
 		}
+
+		// update host usage
+		query := `UPDATE hosts SET usage_account_funding = usage_account_funding + $1, usage_total_spent = usage_total_spent + $2 WHERE id = $3`
```
Comment (ChrisSchinnerl) [inline persist/postgres/contracts.go]: If you use the public key for the host here you can extract this and other duplicated calls into a helper function.

File: client/client.go (hunk 1 above)
Comment (ChrisSchinnerl) [reply client/client.go]: This doesn't seem quite right. When `withRevision` is used, we execute an RPC that is paid for by contract. Considering that we call `syncRevision` after the RPC failed, `usage` should be 0 since the contract wasn't revised.

On the other hand I'm missing something like the following in here 
```go
missedUsage := revision.RemainingAllowance().Sub(resp.Contract.RemainingAllowance())
```
before calling `UpdateContractRevision` with `missedUsage` to catch up on any contract spending we missed.

**Review by ChrisSchinnerl — CHANGES_REQUESTED** [review]

File: client/client.go (hunk 1 above)
Comment (peterjan) [reply client/client.go]: Ah I misunderstood. Thanks, will update PR accordingly

File: persist/postgres/contracts.go (hunk 2 above)
Comment (peterjan) [reply persist/postgres/contracts.go]: Thanks for catching that

**Review by chris124567 — APPROVED** [review]

**Review by ChrisSchinnerl — APPROVED** [review]

**Review by n8mgr — APPROVED** [review]
