### PR TITLE
Fix missing pruning offset

### LINKED ISSUE #627: Investigate Contract Pruning
We see a dramatic increase in lost sectors whenever data is removed from contracts. There may be an issue with how we are determining the indices to prune on the indexer side or the host side might be deleting the incorrect indices.

### PR DESCRIPTION
**Pull request by n8mgr**
Pruning currently deletes arbitrary sectors from the start of the contract since it does not account for the current offset when calling `FreeSectors` with a batch.

Fixes #627

### CODE REVIEW

**Review by chris124567 — APPROVED** [review]

File: contracts/pruning.go [hunk 1]
```diff
@@ -161,7 +161,7 @@ func (cm *ContractManager) pruneContract(ctx context.Context, client HostClient,
 		var indices []uint64
 		for i, root := range res.Roots {
 			if _, found := prunable[root]; found {
-				indices = append(indices, uint64(i))
+				indices = append(indices, offset+uint64(i))
```
Comment (peterjan) [inline contracts/pruning.go:164]: WOW! This needs a regression test. I'm looking into why our tests didn't catch this :/.

**Review by peterjan — CHANGES_REQUESTED** [review]

**Review by peterjan — APPROVED** [review]
I'll F/U with a PR that extends `TestContractPruning` - testing 1TB contracts in testing might be tricky 😅 
(maybe this warrants a test option in the contracts manager though)

**Review by ChrisSchinnerl — APPROVED** [review]
