### PR TITLE
Mark unsynced contracts bad

### LINKED ISSUE #630: Mark contracts bad when we have a newer revision than the host
We have 5 hosts for which we get the error `failed to sync revision: local revision is newer than host revision`. This means we are kind of stuck on these contracts since we can't recover from it.

So when we identify this issue, we should mark that contract as bad and log a warning when doing so. That way, any data on that contract will be migrated away from it.

### PR DESCRIPTION
**Pull request by peterjan**
Fixes #630

### CODE REVIEW

File: client/client.go [hunk 1]
```diff
@@ -57,6 +57,7 @@ type (
 	RevisionStore interface {
 		ContractRevision(ctx context.Context, contractID types.FileContractID) (rhp.ContractRevision, bool, error)
 		UpdateContractRevision(ctx context.Context, contract rhp.ContractRevision, usage proto.Usage) error
+		MarkContractBad(ctx context.Context, contractID types.FileContractID) error
```
Comment (peterjan) [inline client/client.go:60]: It took everything I had to not refactor this. I don't think the client should have a `RevisionStore`, it should have a `ContractManager`. This sends you down quite the rabbit hole though, so I opted for a minimum LoC PR instead.

**Review by chris124567 — APPROVED** [review]

**Review by n8mgr — APPROVED** [review]
