### PR TITLE
Use fallback resolver if OS fails when getting host IP addresses

### LINKED ISSUE #709: Use nomad's fallback when resolving hostnames
nomad falls back to Cloudflare if the local resolver fails. We should use that in indexd to make lookups more robust.

### PR DESCRIPTION
**Pull request by chris124567**
Close #709

### CODE REVIEW

File: hosts/manager.go [hunk 1]
```diff
@@ -200,13 +200,21 @@ func (hm *HostManager) UnblockHost(ctx context.Context, hk types.PublicKey) erro
 
 // NewManager creates a new host manager.
 func NewManager(syncer Syncer, locator Locator, client HostClient, store Store, opts ...Option) (*HostManager, error) {
+	// uses Cloudflare 1.1.1.1 for when OS resolver fails
+	fallbackResolver := &net.Resolver{
+		PreferGo: true,
+		Dial: func(ctx context.Context, network, address string) (net.Conn, error) {
+			return (&net.Dialer{}).DialContext(ctx, network, "1.1.1.1:53")
```
Comment (peterjan) [inline hosts/manager.go:209]: `nit` might want to reuse the dialer here instead of allocating a new one on each dial

File: hosts/manager.go [hunk 2]
```diff
@@ -200,13 +200,21 @@ func (hm *HostManager) UnblockHost(ctx context.Context, hk types.PublicKey) erro
 
 // NewManager creates a new host manager.
 func NewManager(syncer Syncer, locator Locator, client HostClient, store Store, opts ...Option) (*HostManager, error) {
+	// uses Cloudflare 1.1.1.1 for when OS resolver fails
+	fallbackResolver := &net.Resolver{
+		PreferGo: true,
```
Comment (peterjan) [inline hosts/manager.go:207]: Maybe drop a small comment indicating why this has to be `true`. It's because it forces usage of the `Dial` function we specify here right? Otherwise it might use the systems resolver? Docs are a little unclear

File: hosts/manager.go (hunk 1 above)
Comment (ChrisSchinnerl) [reply hosts/manager.go:209]: This should be fine. It's a common pattern that we use ourselves in other places. `net.Dial` itself creates a new one every time as well.

File: hosts/utils_test.go [hunk 3]
```diff
@@ -42,3 +46,67 @@ func TestOnlineChecker(t *testing.T) {
...
+type mockResolverFallback struct {
+	addrs []net.IPAddr
+	err   error
+}
+
+func (m *mockResolverFallback) LookupIPAddr(ctx context.Context, host string) ([]net.IPAddr, error) {
+	return m.addrs, m.err
+}
+
+func TestResolver_LookupIPAddr(t *testing.T) {
```
Comment (ChrisSchinnerl) [inline hosts/utils_test.go]:
```suggestion
func TestResolver(t *testing.T) {
```

That should be fine. No need to introduce a new naming convention for tests.

File: hosts/utils_test.go [hunk 4]
```diff
@@ -42,3 +46,67 @@ func TestOnlineChecker(t *testing.T) {
...
+	ctx := context.Background()
```
Comment (ChrisSchinnerl) [inline hosts/utils_test.go]: Make use of `t.Context()` instead and inline it. It's only used in one spot.

**Review by ChrisSchinnerl — CHANGES_REQUESTED** [review]

**Review by ChrisSchinnerl — APPROVED** [review]

**Review by n8mgr — APPROVED** [review]
