### PR TITLE
Ignore full hosts during migration

### LINKED ISSUE #642: Migrations out of storage
Check whether we are actively trying to write sectors to completely full hosts during migrations. If we are, it needs to be detected and fail early.

### PR DESCRIPTION
**Pull request by chris124567**
Fixes #642

Check that host has at least `MinRemainingStorage` bytes available to be an upload candidate for migrations.

### CODE REVIEW

**Review by n8mgr — CHANGES_REQUESTED** [review]
We want to stop uploading to hosts that have no storage available, not set a leeway if they have remaining storage. An almost full host is still a good host. Probably an indicator it's a very good host.

On the migration end (it may not be broken), since we always scan their settings, I'd check the settings at the scan time. If `remaining storage < SectorSize`, fail early.

**Comment by n8mgr** [comment]
I've split #632 into two issues #642 (fixed by this PR) and #641 for the SDK side of things.

**Review by ChrisSchinnerl — COMMENTED** [review]
To give some additional context to Nate's response. `connPool.uploadShard` would probably be a good spot since that's the closest to the `WriteSector` call. You could return an `ErrNotEnoughStorage` there.

File: slabs/dialer.go [hunk 1]
```diff
@@ -220,6 +223,9 @@ func (c *connPool) uploadShard(ctx context.Context, h hosts.Host, migrationToken
 		if err != nil {
 			return fmt.Errorf("failed to fetch host settings: %w", err)
 		}
+		if settings.RemainingStorage < proto.SectorSize {
+			return errNotEnoughStorage
```
Comment (ChrisSchinnerl) [inline slabs/dialer.go]: If you reuse the `photo.ErrNotEnoughStorage` error you can avoid the change to `retry` since it should be caught by `proto.ErrorCode(err) != proto.ErrorCodeTransport` then.

e.g. `return fmt.Errorf("%w: remaining storage less than sector size", proto.ErrNotEnoughStorage)`

**Review by ChrisSchinnerl — CHANGES_REQUESTED** [review]

File: slabs/dialer.go [hunk 2]
```diff
@@ -220,6 +223,9 @@ func (c *connPool) uploadShard(ctx context.Context, h hosts.Host, migrationToken
 		if err != nil {
 			return fmt.Errorf("failed to fetch host settings: %w", err)
 		}
+		if settings.RemainingStorage < proto.SectorSize {
```
Comment (n8mgr) [inline slabs/dialer.go]: The doc string for `RemainingStorage` says that its in sectors, so this should be `< 1` or `<= 0`

**Review by n8mgr — CHANGES_REQUESTED** [review]

**Review by n8mgr — APPROVED** [review]

**Comment by chris124567** [comment]
Failing cause of TestContractPruning NDF

**Review by ChrisSchinnerl — APPROVED** [review]
