### PR TITLE
Fix master

### LINKED ISSUE #590: Fix TestDownloadCandidates NDF
https://github.com/SiaFoundation/indexd/actions/runs/18849211346/job/53781287543#step:6:255

### PR DESCRIPTION
**Pull request by peterjan**
Fixes master after merging https://github.com/SiaFoundation/indexd/pull/588 

Fixes https://github.com/SiaFoundation/indexd/issues/590

### CODE REVIEW

**Review by ChrisSchinnerl — APPROVED** [review]

**Review by ChrisSchinnerl — CHANGES_REQUESTED** [review]
Seems like we got one more NDF that's possibly related

**Comment by peterjan** [comment]
> Seems like we got one more NDF that's possibly related

one does not simply randomize hosts in the download code 😅

File: slabs/downloads_test.go [hunk 1]
```diff
@@ -197,15 +213,21 @@ func TestDownloadShards(t *testing.T) {
 			t.Fatal(err)
 		} else if !reflect.DeepEqual(sectors, [][]byte{nil, sector2[:], sector3[:]}) {
 			t.Fatal("downloaded sectors do not match expected sectors")
-		} else if sectors := store.lostSectors[hk1]; len(sectors) != 1 {
-			t.Fatalf("expected 1 lost sector for host %v, got %d", hk1, len(store.lostSectors[hk1]))
-		} else if _, ok := sectors[proto.SectorRoot(&sector1)]; !ok {
-			t.Fatalf("expected sector %v to be marked as lost, but it wasn't", proto.SectorRoot(&sector1))
+		}
+
+		if len(store.lostSectors) > 0 {
```
Comment (peterjan) [inline slabs/downloads_test.go]: since we run `minShards` download workers in parallel we can't influence whether we try h1 here

Comment (ChrisSchinnerl) [reply slabs/downloads_test.go]: Can't we delete the hosts we don't want to try from the dialer? Or make them fail?

We can't randomly let this subtest pass without testing what needs to be tested.

File: slabs/downloads_test.go [hunk 2]
```diff
@@ -165,18 +157,42 @@ func TestDownloadShards(t *testing.T) {
...
+		for _, shard := range sectors {
+			if shard == nil {
+				continue
+			}
+			nFetched++
+
+			// sanity check
+			isS1 := bytes.Equal(shard, sector1[:])
+			isS2 := bytes.Equal(shard, sector2[:])
+			isS3 := bytes.Equal(shard, sector3[:])
```
Comment (ChrisSchinnerl) [inline slabs/downloads_test.go]: This doesn't seem right. `downloadShards` should always return the sectors according to their oder in the slab. We rely on that in the migration code since the offset within the result affects the nonce we use for decrypting the data.

**Review by ChrisSchinnerl — CHANGES_REQUESTED** [review]

File: slabs/downloads_test.go (hunk 2 above)
Comment (peterjan) [reply slabs/downloads_test.go]: I rewrote it. I wanted to assert we have `minShard` sectors and they match up.

File: slabs/downloads_test.go (hunk 1 above)
Comment (peterjan) [reply slabs/downloads_test.go]: We can't test the case where the download succeeds, but one of the sectors was marked as lost. I updated it to assert a lost sector is marked as lost, because that's what it's really about anyway. We can't influence what hosts the download code tries first, so if it we mock a lost sector on h1, it might try h2 and h3 and then the download succeeds.

We can rewrite this in a way we _can_ influence this but I don't really see the point. Fine with doing that though if you disagree and feel it's necessary.

File: slabs/downloads_test.go [hunk 3]
```diff
@@ -69,19 +78,12 @@ func TestDownloadShards(t *testing.T) {
 	store := newMockStore()
 	am := newMockAccountManager(store)
 	hm := newMockHostManager()
-	account := types.GeneratePrivateKey()
-
-	settings := func(egress uint64) proto.HostSettings {
-		settings := goodSettings
-		settings.Prices.EgressPrice = types.NewCurrency64(egress)
-		return settings
```
Comment (ChrisSchinnerl) [inline slabs/downloads_test.go:77]: This is a good example of why we shouldn't refactor whenever we get the chance. Especially when in a rush to fix something.

By using `goodSettings` directly you end up 
1. breaking the assertions at the end of the test (you can put any number of sectors in and it will pass)
2. removing context about the pricing from a test that checks balances and moving it to a spot where it is easy to change without being aware of the consequences it might cause

**Review by ChrisSchinnerl — CHANGES_REQUESTED** [review]

File: slabs/downloads_test.go (hunk 3 above)
Comment (peterjan) [reply slabs/downloads_test.go:77]: We removed sorting so I still feel it's necessary to stop initialising hosts with different price settings. I added an assertion though that all hosts should have a non-zero read sector cost.

**Review by ChrisSchinnerl — APPROVED** [review]
